name: Continuous Integration
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 21
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ github.run_id }}
      - run: yarn install
      - run: yarn build
      - name: Generate subgraph.yaml for Sepolia
        working-directory: packages/subgraph
        run: yarn prepare:sepolia
      - name: Run subgraph tests
        working-directory: packages/subgraph
        run: yarn test
