name: Dev Continuous Deployment

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Setup fleek config file
        working-directory: packages/app
        run: cp ./.fleek.dev.json ./.fleek.json
      - name: Deploy site
        working-directory: packages/app
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
      - name: Prep graph cli for deployment
        working-directory: packages/subgraph
        run: yarn run graph auth --product hosted-service ${{ secrets.GRAPH_ACCESS_TOKEN }}
      - name: Deploy subgraphs
        working-directory: packages/subgraph
        env:
          HOSTED_SERVICE_SUBGRAPH__RINKEBY: samepant/tabula-dev
        run: yarn deploy:rinkeby
