name: Dev Continuous Deployment

on:
  push:
    branches: main

env:
  VITE_APP_POSTER_CONTRACT: ${{ secrets.VITE_APP_POSTER_CONTRACT }}
  VITE_APP_INFURA_NETWORK_ACCESS_KEY: ${{ secrets.VITE_APP_INFURA_NETWORK_ACCESS_KEY }}
  VITE_APP_INFURA_IPFS_API_KEY: ${{ secrets.VITE_APP_INFURA_IPFS_API_KEY }}
  VITE_APP_INFURA_IPFS_API_SECRET: ${{ secrets.VITE_APP_INFURA_IPFS_API_SECRET }}
  VITE_APP_SUBGRAPH_BASE_URL: https://api.thegraph.com/subgraphs/name/
  VITE_APP_SUBGRAPH_GNOSIS_CHAIN: auryn-macmillan/tabula-gnosis-chain
  VITE_APP_SUBGRAPH_MAINNET: auryn-macmillan/tabula-mainnet
  VITE_APP_SUBGRAPH_SEPOLIA: auryn-macmillan/tabula-sepolia
  VITE_APP_SUBGRAPH_POLYGON: auryn-macmillan/tabula-polygon
  VITE_APP_SUBGRAPH_ARBITRUM: auryn-macmillan/tabula-arbitrum
  VITE_APP_SUBGRAPH_OPTIMISM: auryn-macmillan/tabula-optimism
  VITE_APP_SUBGRAPH_OPTIMISM_ON_GNOSIS_CHAIN: auryn-macmillan/tabula-optimism-on-gnosis-chain
  VITE_APP_IPFS_GATEWAY: https://ipfs.io/ipfs
  VITE_APP_ENS_SUBGRAPH_MAINNET: ensdomains/ens
  VITE_APP_ENS_SUBGRAPH_SEPOLIA: ensdomains/enssepolia
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 21
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
        with:
          pin-name: Tabula - Latest — ${ GITHUB_SHA }
          path: "./packages/app/dist"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Pin to Crust
        uses: crustio/ipfs-crust-action@v2.0.3
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "tabula.gg"
          RECORD_NAME: "_dnslink.dev"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Get IPFS url
        run: echo "IPFS gateways — https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/ or https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/"

      # - name: Authenticate graph cli studio
      #   working-directory: packages/subgraph
      #   run: yarn run graph auth --studio ${{ secrets.SUBGRAPH_DEPLOYMENT_KEY }}

      - name: Authenticate graph cli hosted service
        working-directory: packages/subgraph
        run: yarn run graph auth --product hosted-service ${{ secrets.GRAPH_ACCESS_TOKEN }}

      - name: Deploy Sepolia subgraphs
        working-directory: packages/subgraph
        env:
          HOSTED_SERVICE_SUBGRAPH__SEPOLIA: auryn-macmillan/tabula-sepolia
        run: yarn deploy:sepolia
