name: Dev Continuous Deployment

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn install --frozen-lockfile
        working-directory: packages/app
      - run: yarn build
        working-directory: packages/app
      - name: Setup fleek config file
        run: cp ./.fleek.dev.json ./.fleek.json
      - name: Deploy site
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
